version: "3.8"

services:
  backend:
    build: ./backend   # path to Spring Boot project
    container_name: backend
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend  # path to React project
    container_name: frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - backend